import { MigrationInterface, QueryRunner } from "typeorm";

export class AddBoetosTaskFields1750684957517 implements MigrationInterface {
    name = 'AddBoetosTaskFields1750684957517'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "user_voice_settings" DROP CONSTRAINT "FK_user_voice_settings_user"`);
        await queryRunner.query(`ALTER TABLE "user_preferences" DROP CONSTRAINT "FK_user_preferences_user"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "FK_users_voice_settings"`);
        await queryRunner.query(`ALTER TABLE "mental_health_checks" DROP CONSTRAINT "FK_mental_health_checks_user"`);
        await queryRunner.query(`ALTER TABLE "memory_entries" DROP CONSTRAINT "FK_memory_entries_user"`);
        await queryRunner.query(`ALTER TABLE "calendar_events" DROP CONSTRAINT "FK_calendar_events_user"`);
        await queryRunner.query(`ALTER TABLE "burnout_thresholds" DROP CONSTRAINT "FK_burnout_thresholds_user"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_mental_health_user_date"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_calendar_events_user_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_calendar_events_start_time"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_calendar_events_external_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_burnout_thresholds_user_id"`);
        await queryRunner.query(`CREATE TABLE "user_schedule" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "event_id" character varying, "title" character varying, "description" text, "start_time" TIMESTAMP, "end_time" TIMESTAMP, "location" character varying, "event_type" character varying, "source" character varying, "is_all_day" boolean NOT NULL DEFAULT false, "status" character varying, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_1c68f6861388e111e080b7ea766" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "stress_patterns" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" character varying NOT NULL, "patternType" character varying NOT NULL, "description" text NOT NULL, "severity" character varying NOT NULL, "frequency" character varying NOT NULL, "detectedAt" TIMESTAMP NOT NULL, "metadata" jsonb, CONSTRAINT "PK_9b5cc14c1846481ae4849dd7405" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_STRESS_PATTERN_USER_DATE" ON "stress_patterns" ("userId", "detectedAt") `);
        await queryRunner.query(`CREATE TABLE "meeting" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "title" character varying NOT NULL, "description" character varying, "start_time" TIMESTAMP NOT NULL, "end_time" TIMESTAMP NOT NULL, "participants" jsonb, "google_calendar_event_id" character varying, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_dccaf9e4c0e39067d82ccc7bb83" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "activity" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "type" character varying NOT NULL, "description" character varying, "metadata" jsonb, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_24625a1d6b1b089c8ae206fe467" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "profile_image"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "avatar"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "google_access_token"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "google_refresh_token"`);
        await queryRunner.query(`ALTER TABLE "ai_intervention_rule" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "ai_intervention_rule" DROP COLUMN "description"`);
        await queryRunner.query(`ALTER TABLE "calendar_events" ADD "boetos_task_state" character varying DEFAULT 'active'`);
        await queryRunner.query(`COMMENT ON COLUMN "calendar_events"."boetos_task_state" IS 'State of Boetos Task (active, paused, completed, cancelled)'`);
        await queryRunner.query(`ALTER TABLE "calendar_events" ADD "timer_state" jsonb`);
        await queryRunner.query(`COMMENT ON COLUMN "calendar_events"."timer_state" IS 'Timer state for Boetos Task (remaining, lastStarted, pausedAt, etc)'`);
        await queryRunner.query(`ALTER TABLE "calendar_events" ADD "is_boetos_task" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`COMMENT ON COLUMN "calendar_events"."is_boetos_task" IS 'True if this event is a Boetos Task'`);
        await queryRunner.query(`ALTER TABLE "calendar_events" ADD "analytics" jsonb`);
        await queryRunner.query(`COMMENT ON COLUMN "calendar_events"."analytics" IS 'Analytics for Boetos Task (startedAt, completedAt, cancelledAt, etc)'`);
        await queryRunner.query(`ALTER TABLE "calendar_events" ADD "reminder_time" TIMESTAMP`);
        await queryRunner.query(`COMMENT ON COLUMN "calendar_events"."reminder_time" IS 'Reminder time for Boetos Task'`);
        await queryRunner.query(`ALTER TABLE "ai_intervention_rule" ADD "rule_name" character varying`);
        await queryRunner.query(`ALTER TABLE "ai_intervention_rule" ADD "is_active" boolean NOT NULL DEFAULT true`);
        await queryRunner.query(`ALTER TABLE "ai_intervention_rule" ADD "user_id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "user_voice_settings" ADD CONSTRAINT "UQ_4aa4bb4b5412d6b040ef5089a9c" UNIQUE ("user_id")`);
        await queryRunner.query(`ALTER TABLE "user_voice_settings" ALTER COLUMN "voice_enabled" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "user_voice_settings" ALTER COLUMN "voice_speed" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "user_voice_settings" ALTER COLUMN "voice_speed" SET DEFAULT '1'`);
        await queryRunner.query(`ALTER TABLE "user_voice_settings" ALTER COLUMN "voice_pitch" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "user_voice_settings" ALTER COLUMN "voice_pitch" SET DEFAULT '1'`);
        await queryRunner.query(`ALTER TABLE "user_voice_settings" ALTER COLUMN "voice_volume" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "user_voice_settings" ALTER COLUMN "voice_volume" SET DEFAULT '1'`);
        await queryRunner.query(`ALTER TABLE "user_voice_settings" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "user_voice_settings" ALTER COLUMN "updated_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "user_preferences" ADD CONSTRAINT "UQ_458057fa75b66e68a275647da2e" UNIQUE ("user_id")`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "name" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "UQ_345f5109761749b6a8e3f90ca1d" UNIQUE ("voice_settings_id")`);
        await queryRunner.query(`ALTER TABLE "calendar_events" ALTER COLUMN "is_all_day" SET NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "calendar_events"."event_type" IS 'meeting, focus, break, personal'`);
        await queryRunner.query(`COMMENT ON COLUMN "calendar_events"."calendar_source" IS 'google, outlook, manual'`);
        await queryRunner.query(`COMMENT ON COLUMN "calendar_events"."stress_impact" IS 'Estimated stress impact of the event (-1 to 1)'`);
        await queryRunner.query(`ALTER TABLE "calendar_events" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "calendar_events" ALTER COLUMN "updated_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "burnout_thresholds" ADD CONSTRAINT "UQ_f22ff57ecf77deece8d2de1dfbc" UNIQUE ("user_id")`);
        await queryRunner.query(`ALTER TABLE "burnout_thresholds" ALTER COLUMN "max_meeting_hours_per_day" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "burnout_thresholds" ALTER COLUMN "max_meeting_hours_per_day" SET DEFAULT '4'`);
        await queryRunner.query(`ALTER TABLE "burnout_thresholds" ALTER COLUMN "max_work_hours_per_day" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "burnout_thresholds" ALTER COLUMN "max_work_hours_per_day" SET DEFAULT '8'`);
        await queryRunner.query(`ALTER TABLE "burnout_thresholds" ALTER COLUMN "min_break_hours_per_day" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "burnout_thresholds" ALTER COLUMN "min_break_hours_per_day" SET DEFAULT '1'`);
        await queryRunner.query(`ALTER TABLE "burnout_thresholds" ALTER COLUMN "min_focus_blocks_per_day" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "burnout_thresholds" ALTER COLUMN "min_focus_blocks_per_day" SET DEFAULT '2'`);
        await queryRunner.query(`ALTER TABLE "burnout_thresholds" ALTER COLUMN "min_sleep_hours" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "burnout_thresholds" ALTER COLUMN "min_sleep_hours" SET DEFAULT '7'`);
        await queryRunner.query(`ALTER TABLE "burnout_thresholds" ALTER COLUMN "meeting_weight" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "burnout_thresholds" ALTER COLUMN "meeting_weight" SET DEFAULT '0.3'`);
        await queryRunner.query(`ALTER TABLE "burnout_thresholds" ALTER COLUMN "work_hours_weight" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "burnout_thresholds" ALTER COLUMN "work_hours_weight" SET DEFAULT '0.2'`);
        await queryRunner.query(`ALTER TABLE "burnout_thresholds" ALTER COLUMN "break_weight" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "burnout_thresholds" ALTER COLUMN "break_weight" SET DEFAULT '0.15'`);
        await queryRunner.query(`ALTER TABLE "burnout_thresholds" ALTER COLUMN "focus_weight" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "burnout_thresholds" ALTER COLUMN "focus_weight" SET DEFAULT '0.2'`);
        await queryRunner.query(`ALTER TABLE "burnout_thresholds" ALTER COLUMN "sleep_weight" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "burnout_thresholds" ALTER COLUMN "sleep_weight" SET DEFAULT '0.15'`);
        await queryRunner.query(`ALTER TABLE "burnout_thresholds" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "burnout_thresholds" ALTER COLUMN "updated_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "burnout_scores" DROP COLUMN "stress_indicators"`);
        await queryRunner.query(`ALTER TABLE "burnout_scores" ADD "stress_indicators" text`);
        await queryRunner.query(`ALTER TABLE "burnout_scores" DROP COLUMN "recovery_indicators"`);
        await queryRunner.query(`ALTER TABLE "burnout_scores" ADD "recovery_indicators" text`);
        await queryRunner.query(`ALTER TABLE "ai_intervention_rule" DROP CONSTRAINT "ai_intervention_rule_pkey"`);
        await queryRunner.query(`ALTER TABLE "ai_intervention_rule" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "ai_intervention_rule" ADD "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "ai_intervention_rule" ADD CONSTRAINT "PK_016d3fa649425229869a94d2b69" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "ai_intervention_rule" ALTER COLUMN "rule_condition" SET NOT NULL`);
        await queryRunner.query(`CREATE INDEX "IDX_MENTAL_HEALTH_USER_DATE" ON "mental_health_checks" ("user_id", "created_at") `);
        await queryRunner.query(`ALTER TABLE "user_voice_settings" ADD CONSTRAINT "FK_4aa4bb4b5412d6b040ef5089a9c" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_schedule" ADD CONSTRAINT "FK_ed398d25ddca913e979a0fca21f" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_preferences" ADD CONSTRAINT "FK_458057fa75b66e68a275647da2e" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "FK_345f5109761749b6a8e3f90ca1d" FOREIGN KEY ("voice_settings_id") REFERENCES "user_voice_settings"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "mental_health_checks" ADD CONSTRAINT "FK_177c7f4769290ce2d2ea22db47b" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "memory_entries" ADD CONSTRAINT "FK_89a846cb567eace91491952da3f" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "meeting" ADD CONSTRAINT "FK_1fa331d01d59dd6a7d408788e61" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "calendar_events" ADD CONSTRAINT "FK_7f9a3d7f6217b99b6b2431887df" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "burnout_thresholds" ADD CONSTRAINT "FK_f22ff57ecf77deece8d2de1dfbc" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "burnout_scores" ADD CONSTRAINT "FK_35beebff2fc226fa8ab1611494c" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ai_intervention_rule" ADD CONSTRAINT "FK_5a2f85f82e6bc19bf4df4b61b27" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "activity" ADD CONSTRAINT "FK_10bf0c2dd4736190070e8475119" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "activity" DROP CONSTRAINT "FK_10bf0c2dd4736190070e8475119"`);
        await queryRunner.query(`ALTER TABLE "ai_intervention_rule" DROP CONSTRAINT "FK_5a2f85f82e6bc19bf4df4b61b27"`);
        await queryRunner.query(`ALTER TABLE "burnout_scores" DROP CONSTRAINT "FK_35beebff2fc226fa8ab1611494c"`);
        await queryRunner.query(`ALTER TABLE "burnout_thresholds" DROP CONSTRAINT "FK_f22ff57ecf77deece8d2de1dfbc"`);
        await queryRunner.query(`ALTER TABLE "calendar_events" DROP CONSTRAINT "FK_7f9a3d7f6217b99b6b2431887df"`);
        await queryRunner.query(`ALTER TABLE "meeting" DROP CONSTRAINT "FK_1fa331d01d59dd6a7d408788e61"`);
        await queryRunner.query(`ALTER TABLE "memory_entries" DROP CONSTRAINT "FK_89a846cb567eace91491952da3f"`);
        await queryRunner.query(`ALTER TABLE "mental_health_checks" DROP CONSTRAINT "FK_177c7f4769290ce2d2ea22db47b"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "FK_345f5109761749b6a8e3f90ca1d"`);
        await queryRunner.query(`ALTER TABLE "user_preferences" DROP CONSTRAINT "FK_458057fa75b66e68a275647da2e"`);
        await queryRunner.query(`ALTER TABLE "user_schedule" DROP CONSTRAINT "FK_ed398d25ddca913e979a0fca21f"`);
        await queryRunner.query(`ALTER TABLE "user_voice_settings" DROP CONSTRAINT "FK_4aa4bb4b5412d6b040ef5089a9c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_MENTAL_HEALTH_USER_DATE"`);
        await queryRunner.query(`ALTER TABLE "ai_intervention_rule" ALTER COLUMN "rule_condition" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "ai_intervention_rule" DROP CONSTRAINT "PK_016d3fa649425229869a94d2b69"`);
        await queryRunner.query(`ALTER TABLE "ai_intervention_rule" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "ai_intervention_rule" ADD "id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "ai_intervention_rule" ADD CONSTRAINT "ai_intervention_rule_pkey" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "burnout_scores" DROP COLUMN "recovery_indicators"`);
        await queryRunner.query(`ALTER TABLE "burnout_scores" ADD "recovery_indicators" jsonb`);
        await queryRunner.query(`ALTER TABLE "burnout_scores" DROP COLUMN "stress_indicators"`);
        await queryRunner.query(`ALTER TABLE "burnout_scores" ADD "stress_indicators" jsonb`);
        await queryRunner.query(`ALTER TABLE "burnout_thresholds" ALTER COLUMN "updated_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "burnout_thresholds" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "burnout_thresholds" ALTER COLUMN "sleep_weight" SET DEFAULT 0.15`);
        await queryRunner.query(`ALTER TABLE "burnout_thresholds" ALTER COLUMN "sleep_weight" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "burnout_thresholds" ALTER COLUMN "focus_weight" SET DEFAULT 0.2`);
        await queryRunner.query(`ALTER TABLE "burnout_thresholds" ALTER COLUMN "focus_weight" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "burnout_thresholds" ALTER COLUMN "break_weight" SET DEFAULT 0.15`);
        await queryRunner.query(`ALTER TABLE "burnout_thresholds" ALTER COLUMN "break_weight" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "burnout_thresholds" ALTER COLUMN "work_hours_weight" SET DEFAULT 0.2`);
        await queryRunner.query(`ALTER TABLE "burnout_thresholds" ALTER COLUMN "work_hours_weight" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "burnout_thresholds" ALTER COLUMN "meeting_weight" SET DEFAULT 0.3`);
        await queryRunner.query(`ALTER TABLE "burnout_thresholds" ALTER COLUMN "meeting_weight" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "burnout_thresholds" ALTER COLUMN "min_sleep_hours" SET DEFAULT 7.0`);
        await queryRunner.query(`ALTER TABLE "burnout_thresholds" ALTER COLUMN "min_sleep_hours" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "burnout_thresholds" ALTER COLUMN "min_focus_blocks_per_day" SET DEFAULT 2.0`);
        await queryRunner.query(`ALTER TABLE "burnout_thresholds" ALTER COLUMN "min_focus_blocks_per_day" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "burnout_thresholds" ALTER COLUMN "min_break_hours_per_day" SET DEFAULT 1.0`);
        await queryRunner.query(`ALTER TABLE "burnout_thresholds" ALTER COLUMN "min_break_hours_per_day" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "burnout_thresholds" ALTER COLUMN "max_work_hours_per_day" SET DEFAULT 8.0`);
        await queryRunner.query(`ALTER TABLE "burnout_thresholds" ALTER COLUMN "max_work_hours_per_day" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "burnout_thresholds" ALTER COLUMN "max_meeting_hours_per_day" SET DEFAULT 4.0`);
        await queryRunner.query(`ALTER TABLE "burnout_thresholds" ALTER COLUMN "max_meeting_hours_per_day" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "burnout_thresholds" DROP CONSTRAINT "UQ_f22ff57ecf77deece8d2de1dfbc"`);
        await queryRunner.query(`ALTER TABLE "calendar_events" ALTER COLUMN "updated_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "calendar_events" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "calendar_events"."stress_impact" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "calendar_events"."calendar_source" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "calendar_events"."event_type" IS NULL`);
        await queryRunner.query(`ALTER TABLE "calendar_events" ALTER COLUMN "is_all_day" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "UQ_345f5109761749b6a8e3f90ca1d"`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "name" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "user_preferences" DROP CONSTRAINT "UQ_458057fa75b66e68a275647da2e"`);
        await queryRunner.query(`ALTER TABLE "user_voice_settings" ALTER COLUMN "updated_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "user_voice_settings" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "user_voice_settings" ALTER COLUMN "voice_volume" SET DEFAULT 1.0`);
        await queryRunner.query(`ALTER TABLE "user_voice_settings" ALTER COLUMN "voice_volume" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "user_voice_settings" ALTER COLUMN "voice_pitch" SET DEFAULT 1.0`);
        await queryRunner.query(`ALTER TABLE "user_voice_settings" ALTER COLUMN "voice_pitch" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "user_voice_settings" ALTER COLUMN "voice_speed" SET DEFAULT 1.0`);
        await queryRunner.query(`ALTER TABLE "user_voice_settings" ALTER COLUMN "voice_speed" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "user_voice_settings" ALTER COLUMN "voice_enabled" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "user_voice_settings" DROP CONSTRAINT "UQ_4aa4bb4b5412d6b040ef5089a9c"`);
        await queryRunner.query(`ALTER TABLE "ai_intervention_rule" DROP COLUMN "user_id"`);
        await queryRunner.query(`ALTER TABLE "ai_intervention_rule" DROP COLUMN "is_active"`);
        await queryRunner.query(`ALTER TABLE "ai_intervention_rule" DROP COLUMN "rule_name"`);
        await queryRunner.query(`COMMENT ON COLUMN "calendar_events"."reminder_time" IS 'Reminder time for Boetos Task'`);
        await queryRunner.query(`ALTER TABLE "calendar_events" DROP COLUMN "reminder_time"`);
        await queryRunner.query(`COMMENT ON COLUMN "calendar_events"."analytics" IS 'Analytics for Boetos Task (startedAt, completedAt, cancelledAt, etc)'`);
        await queryRunner.query(`ALTER TABLE "calendar_events" DROP COLUMN "analytics"`);
        await queryRunner.query(`COMMENT ON COLUMN "calendar_events"."is_boetos_task" IS 'True if this event is a Boetos Task'`);
        await queryRunner.query(`ALTER TABLE "calendar_events" DROP COLUMN "is_boetos_task"`);
        await queryRunner.query(`COMMENT ON COLUMN "calendar_events"."timer_state" IS 'Timer state for Boetos Task (remaining, lastStarted, pausedAt, etc)'`);
        await queryRunner.query(`ALTER TABLE "calendar_events" DROP COLUMN "timer_state"`);
        await queryRunner.query(`COMMENT ON COLUMN "calendar_events"."boetos_task_state" IS 'State of Boetos Task (active, paused, completed, cancelled)'`);
        await queryRunner.query(`ALTER TABLE "calendar_events" DROP COLUMN "boetos_task_state"`);
        await queryRunner.query(`ALTER TABLE "ai_intervention_rule" ADD "description" text`);
        await queryRunner.query(`ALTER TABLE "ai_intervention_rule" ADD "name" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ADD "google_refresh_token" character varying`);
        await queryRunner.query(`ALTER TABLE "users" ADD "google_access_token" character varying`);
        await queryRunner.query(`ALTER TABLE "users" ADD "avatar" character varying`);
        await queryRunner.query(`ALTER TABLE "users" ADD "profile_image" character varying`);
        await queryRunner.query(`DROP TABLE "activity"`);
        await queryRunner.query(`DROP TABLE "meeting"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_STRESS_PATTERN_USER_DATE"`);
        await queryRunner.query(`DROP TABLE "stress_patterns"`);
        await queryRunner.query(`DROP TABLE "user_schedule"`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_burnout_thresholds_user_id" ON "burnout_thresholds" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_calendar_events_external_id" ON "calendar_events" ("external_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_calendar_events_start_time" ON "calendar_events" ("start_time") `);
        await queryRunner.query(`CREATE INDEX "IDX_calendar_events_user_id" ON "calendar_events" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_mental_health_user_date" ON "mental_health_checks" ("created_at", "user_id") `);
        await queryRunner.query(`ALTER TABLE "burnout_thresholds" ADD CONSTRAINT "FK_burnout_thresholds_user" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "calendar_events" ADD CONSTRAINT "FK_calendar_events_user" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "memory_entries" ADD CONSTRAINT "FK_memory_entries_user" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "mental_health_checks" ADD CONSTRAINT "FK_mental_health_checks_user" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "FK_users_voice_settings" FOREIGN KEY ("voice_settings_id") REFERENCES "user_voice_settings"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_preferences" ADD CONSTRAINT "FK_user_preferences_user" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_voice_settings" ADD CONSTRAINT "FK_user_voice_settings_user" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

}
